SEED: 0
N_ROBOTS: 2
N_ACTIONS: 8
N_TARGETS: 1
N_CHANNELS: 1
HEIGHT: 200
WIDTH: 200
RESOLUTION: 0.1
CONTEXT: 6
PHYSICS_HZ: 100
UPDATE_HZ: 0.1
SCAN_HZ: 5
MAP_LIST: ["maps/empty.png"]
MAP_REDUCTION_FACTOR: 5
ROBOT_URDF: "robot.urdf"
TARGET_URDF: "target.urdf"
MAX_FOV: 360
MIN_FOV: 60
MAX_VEL: 1
MIN_VEL: 0.1
MAX_RANGE: 3
MIN_RANGE: 1
MAX_STEPS: 10000
WAYPOINT_RADIUS: 3
WAYPOINT_ERROR_COST: 20
COLLISION_COST: 100
DETECTION_REWARD: 1000
K_V: 1
K_P_TH: 0.1
K_V_TH: 1
DECAY_RATE: 1.0

